### ISSUE TITLE
Currently docker images are not versioned which can be an issue going further

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp-facade#62]
**Is your feature request related to a problem? Please describe.**
Docker images for VulnerableApp-facade just have 1 version latest. It should be the latest (whcih is unreleased) and specific tags for released versions.

For more information about the existing images: https://hub.docker.com/r/sasanlabs/owasp-vulnerableapp-facade/tags

**How do we create images ?**
we have a Github action for creating and pushing docker images: https://github.com/SasanLabs/VulnerableApp-facade/blob/main/.github/workflows/docker.yml

**Comment by preetkaran20** [comment]
we have used github semantic versioning in Owasp VulnerableApp project. we can use similar thing here as well.

PR: https://github.com/SasanLabs/VulnerableApp/pull/382

**Comment by merry-degaga** [comment]
Karan, you can assign this to me. 

I think I better understand the 'unreleased' tag. Because you want to manually create a GitHub release, by default, the most recent build/deploys will be tagged as 'unreleased'. Is this correct?

Then would you want functionality, that when someone does manually create a release, that will trigger a workflow, which can use the tag of that newly publish release and also add the 'latest' tag on DockerHub?

Currently, with my most recent PR, the latest docker build/deploy will be tagged with the version number and 'unreleased' tags.

**Comment by preetkaran20** [comment]
@merry-degaga we need the same functionality as we have in VulnerableApp repository and in both the repositories, we need an additional functionality which is to add the latest tag to docker hub.

**Comment by preetkaran20** [comment]
I think both can be part of same ticket.

**Comment by merry-degaga** [comment]
Hi Karan, is it okay to close this issue? 

Thank you

**Comment by preetkaran20** [comment]
> Hi Karan, is it okay to close this issue?
> 
> Thank you

@merry-degaga yes please and thank you!!
